name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.4
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.2

    - name: Publish to RubyGems
      uses: rubygems/release-gem@v1
