name: Ruby

on:
  push:
    paths:
      - 'lib/**'
      - 'spec/**'
  pull_request:
    paths:
      - 'lib/**'
      - 'spec/**'

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3.6', '3.4.2']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install MeCab
      run: apt-get update -qq && apt-get install -y mecab mecab-ipadic-utf8 libmecab-dev
    - name: Run tests
      run: bundle exec rspec
